# Generated by Django 3.1.2 on 2020-10-24 10:52

from django.db import migrations, models
import team.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TSInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=team.models.user_directory_path)),
                ('descript', models.TextField(blank=True, null=True)),
                ('access_auth', models.IntegerField()),
            ],
            options={
                'db_table': 'TeamStorageInfo',
            },
        ),
    ]
