# Generated by Django 3.1.1 on 2020-10-28 06:00

from django.db import migrations, models
import django.db.models.deletion
import team.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=team.models.user_directory_path)),
                ('descript', models.TextField(blank=True, null=True)),
                ('access_auth', models.IntegerField()),
            ],
            options={
                'db_table': 'TeamStorageInfo',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('value', models.TextField()),
                ('input_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
                ('team_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.teamstorage')),
            ],
            options={
                'db_table': 'TeamNotice',
                'unique_together': {('team_storage', 'title')},
            },
        ),
    ]
