# Generated by Django 3.1.1 on 2020-10-27 08:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20201027_1743'),
        ('main', '0002_auto_20201023_1951'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('value', models.TextField()),
                ('input_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
                ('team_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.teamstorage')),
            ],
        ),
    ]
