# Generated by Django 3.1.2 on 2020-10-05 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_storagelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStorage',
            fields=[
                ('storage_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('authority', models.IntegerField(default=0)),
                ('master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'db_table': 'teamstorages',
            },
        ),
    ]
