# Generated by Django 3.1.1 on 2020-10-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamstorage',
            name='authority',
            field=models.IntegerField(default=1),
        ),
    ]
