# Generated by Django 3.1.1 on 2020-10-15 16:17

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PSInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=main.models.user_directory_path)),
                ('descript', models.TextField(null=True)),
            ],
            options={
                'db_table': 'PersonalStorageInfo',
            },
        ),
        migrations.CreateModel(
            name='StorageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_auth', models.IntegerField()),
            ],
            options={
                'db_table': 'storagelists',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_pw', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
