# Generated by Django 3.1.1 on 2020-11-10 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelist',
            name='team_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.teamstorage'),
        ),
        migrations.AddField(
            model_name='storagelist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
