# Generated by Django 3.1.2 on 2020-10-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201005_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_auth', models.IntegerField()),
            ],
            options={
                'db_table': 'storagelists',
            },
        ),
    ]
