# Generated by Django 3.1.2 on 2020-10-05 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('main', '0003_storagelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelist',
            name='team_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.teamstorage'),
        ),
        migrations.AddField(
            model_name='storagelist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
