# Generated by Django 3.1.1 on 2020-10-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201005_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='views.dirpath')),
            ],
            options={
                'db_table': 'PersonalStorageInfo',
            },
        ),
    ]
