# Generated by Django 3.1.1 on 2020-10-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_psinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psinfo',
            name='file',
            field=models.FileField(upload_to='dir_path'),
        ),
    ]
