# Generated by Django 3.1.1 on 2020-10-13 12:41

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201013_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='psinfo',
            name='memo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='psinfo',
            name='file',
            field=models.FileField(upload_to=main.models.user_directory_path),
        ),
    ]
