# Generated by Django 3.1.1 on 2020-10-28 06:00

from django.db import migrations, models
import personal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PSInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=personal.models.user_directory_path)),
                ('descript', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PersonalStorageInfo',
            },
        ),
    ]
